import { useEffect, useRef } from 'react';
import { useTrackerStore } from '../store/trackerStore';
import { useThrottledEntities } from './useThrottledEntities';
import { ResourceTracker } from '../core/trackers/ResourceTracker';

export function useDynamicWaypointRouter() {
  const activeWaypointName = useTrackerStore(state => state.activeWaypointName);
  const currentZone = useTrackerStore(state => state.currentZone);
  const playerPosition = useTrackerStore(state => state.playerPosition);
  
  // Throttle updates to avoid calculating nearest every single frame
  const { enemies, resources, loot } = useThrottledEntities(500);

  const lastNearestPosRef = useRef<{x: number, y: number} | null>(null);

  useEffect(() => {
    if (!activeWaypointName || !playerPosition || !currentZone) {
      lastNearestPosRef.current = null;
      return;
    }

    // Ignore special routing targets generated by death drops or zone pathfinding
    if (
      activeWaypointName.includes('Recover') || 
      activeWaypointName.includes('Entrance') ||
      activeWaypointName.includes('Exit') ||
      activeWaypointName.includes('Return') ||
      activeWaypointName.includes('To ')
    ) {
      lastNearestPosRef.current = null;
      return;
    }

    let nearestPos: {x: number, y: number} | null = null;
    let minSqDist = Infinity;

    const px = playerPosition.x;
    const py = playerPosition.y;

    const checkEntity = (name: string, pos: {x: number, y: number}, zone: string, isAlive: boolean) => {
      if (!isAlive || zone !== currentZone) return;
      
      const sanitized = ResourceTracker.sanitizeResourceName(name);
      if (sanitized === activeWaypointName) {
        const distSq = (pos.x - px) ** 2 + (pos.y - py) ** 2;
        if (distSq < minSqDist) {
          minSqDist = distSq;
          nearestPos = pos;
        }
      }
    };

    // 1. Check all enemies in the current zone
    if (enemies) {
      Object.values(enemies).forEach(e => checkEntity(e.type, e.pos, e.zone || currentZone, !e.isDead));
    }
    
    // 2. Check all resources in the current zone
    if (resources) {
      Object.values(resources).forEach(r => checkEntity(r.resource, r.pos, r.zone || currentZone, !r.gathered));
    }
    
    // 3. Check all loot drops in the current zone
    if (loot) {
      Object.values(loot).forEach(drop => checkEntity(drop.itemName, drop.pos, currentZone, true));
    }

    if (nearestPos) {
      const prev = lastNearestPosRef.current;
      const nPos = nearestPos as {x: number, y: number};
      // Only dispatch state update if the nearest entity has actually shifted to a different coordinate
      if (!prev || prev.x !== nPos.x || prev.y !== nPos.y) {
        lastNearestPosRef.current = nPos;
        useTrackerStore.getState().setActiveWaypoint(nPos, activeWaypointName, currentZone);
      }
    }
  }, [activeWaypointName, currentZone, playerPosition, enemies, resources, loot]);
}
